server:
  port: 9080

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8080/icommerce/
          predicates:
            - Path=/icommerce/v1/product/**
        - id: shopping-cart-service
            uri: http://localhost:8081/icommerce
            predicates:
              - Path=/icommerce/v1/shopping-cart
        - id: customer-service
            uri: http://localhost:8082/icommerce
            predicates:
              - Path=/icommerce/v1/customer
        - id: purchase-order-service
            uri: http://localhost:8083/icommerce
            predicates:
              - Path=/icommerce/v1/purchase-order
  application:
    name: api-gateway-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
